/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Image {
  /** Open an image from a file path (async, non-blocking). */
  static open(path: string): Promise<Image>
  /** Decode an image from a `Buffer` or `Uint8Array` (sync). */
  static fromBuffer(data: Buffer): Image
  /** Image width in pixels. */
  get width(): number
  /** Image height in pixels. */
  get height(): number
  /** Number of channels (1 = gray, 2 = gray+alpha, 3 = RGB, 4 = RGBA). */
  get channels(): number
  /**
   * Resize to `(width, height)` — async, runs on Tokio thread pool.
   *
   * Auto-orients, resizes with the chosen filter and mode, and propagates
   * ICC/EXIF metadata to the result for later injection via `toBuffer`/`save`.
   */
  resize(width: number, height: number, opts?: ResizeOptions | undefined | null): Promise<Image>
  /** Resize sync — blocks the event loop. Use for scripts or worker threads. */
  resizeSync(width: number, height: number, opts?: ResizeOptions | undefined | null): Image
  /** Encode to a `Buffer` — async. ICC + EXIF injected automatically. */
  toBuffer(format?: string | undefined | null, opts?: EncodeOpts | undefined | null): Promise<Buffer>
  /** Encode to a `Buffer` — sync variant. */
  toBufferSync(format?: string | undefined | null, opts?: EncodeOpts | undefined | null): Buffer
  /** Save to a file — async, format inferred from extension. Injects ICC+EXIF. */
  save(path: string, opts?: EncodeOpts | undefined | null): Promise<void>
  /** Clone this image. */
  clone(): Image
  toString(): string
}

export interface EncodeOpts {
  /** JPEG quality 1–100. Ignored for lossless formats. Default `85`. */
  quality?: number
}

export interface ResizeOptions {
  /**
   * Resampling filter. Default `"lanczos"`.
   * One of: nearest, bilinear, bicubic, lanczos, lanczos2, lanczos4,
   * box, hamming, mitchell, catmull_rom, gaussian, hann.
   */
  filter?: string
  /**
   * Resize mode. Default `"fill"`.
   * - `"fill"`       — stretch to exact size
   * - `"fit"`        — fit inside box, pad edges with bgColor
   * - `"cover"`      — fill box, crop from center
   * - `"fit_width"`  — scale to width, height proportional
   * - `"fit_height"` - scale to height, width proportional
   */
  mode?: string
  /** Pre-multiply alpha before resampling (LA/RGBA). Default `true`. */
  premultiplyAlpha?: boolean
  /** Thread count. `0` = adaptive. Default `1`. */
  workers?: number
  /** Background color for `"fit"` padding as `[r, g, b, a]`. Default `[0,0,0,0]`. */
  bgColor?: Array<number>
  /** Copy ICC color profile to output. Default `true`. */
  withIcc?: boolean
  /** Copy EXIF block (orientation reset to 1). Default `true`. */
  withExif?: boolean
  /** Copy XMP block. Default `false`. */
  withXmp?: boolean
  /** Auto-rotate pixels per EXIF orientation before resize. Default `true`. */
  autoOrient?: boolean
}

export declare const enum Workers {
  Adaptive = 'Adaptive',
  Single = 'Single'
}
