workspace = { members = ["app"] }

[package]
name = "pic-scale"
version = "0.1.14"
edition = "2021"
description = "High performance image scaling"
readme = "README.md"
keywords = ["scale", "resize", "image-resize"]
license = "Apache-2.0 OR BSD-3-Clause"
authors = ["Radzivon Bartoshyk"]
documentation = "https://github.com/awxkee/pic-scale"
categories = ["multimedia::images", "multimedia::video"]
homepage = "https://github.com/awxkee/pic-scale"
repository = "https://github.com/awxkee/pic-scale"
exclude = ["*.jpg", "/assets"]

[dependencies]
colorutils-rs = "0.4.8"
num-traits = "0.2.19"
rayon = "1.10.0"
