[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.2", features = ["default"] }
pic-scale = { path = "..", features = ["half", "disable_simd"], default-features = true }
fast_image_resize = { version = "5.0.0", features = ["rayon"] }
half = { version = "2.4.1", default-features = true }

[dev-dependencies]
criterion = "0.5.1"
image = { version = "0.25.2", features = ["default"] }
fast_image_resize = { version = "5.0.0", features = ["rayon"] }
pic-scale = { path = "..", features = ["half", "disable_simd"] }

[[bench]]
name = "resize_rgb"
harness = false

[[bench]]
name = "resize_rgba"
harness = false