[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
pic-scale = { path = "..", features = ["half"] }
fast_image_resize = "4.0.0"
half = { version = "2.4.1", default-features = true }

[dev-dependencies]
criterion = "0.5.1"
image = "0.25.1"
fast_image_resize = "4.0.0"
pic-scale = { path = ".." }

[[bench]]
name = "resize_rgb"
harness = false

[[bench]]
name = "resize_rgba"
harness = false