[target.x86_64-pc-windows-msvc]
#rustflags = ["-C", "target-feature=+f16c,+sse4.1"]
rustflags = ["-Ctarget-cpu=native"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=-fp16"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+sse4.1"]

[target.riscv64gc-unknown-linux-gnu]
rustflags = ["-Ctarget-feature=+rvv", "-Ctarget-cpu=native"]
#linker = "/opt/homebrew/Cellar/riscv-gnu-toolchain/main/bin/riscv64-unknown-elf-gcc"
#ar = "/opt/homebrew/Cellar/riscv-gnu-toolchain/main/bin/riscv64-unknown-elf-ar"

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]

[target.aarch64-linux-android]
ar = "/Users/radzivon/Library/Android/sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/radzivon/Library/Android/sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"

[target.x86_64-linux-android]
ar = "/Users/radzivon/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/radzivon/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android21-clang"

[target.armv7-linux-androideabi]
ar = "/Users/radzivon/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/radzivon/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang"

[target.i686-linux-android]
ar = "/Users/radzivon/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/radzivon/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android21-clang"