name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'v_test_sse'
    tags-ignore:
      - '*'
  pull_request:
    branches-ignore:
      - '*'

jobs:
  tests_x86_sse_isolated:
    name: Testing x86 SSE isolated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: sudo apt-get install -y qemu-user
      - run: cargo +nightly test --features "sse"
        env:
          RUSTFLAGS: "-C target-feature=+sse4.1,-avx,-avx2,-fma"
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: "qemu-x86_64 -cpu Nehalem"